name: ksta
description: KSTA case study app.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.11.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
